version: '3'
services:
  db:
    image: mysql:5.7
    # command: --lower_case_table_names=1
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    container_name: db
