version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
  api:
    image: cristianb1233/featureflags_api
    restart: always
    ports: 
      - 8000:80
    depends_on: 
      - db
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
  web:
    image: cristianb1233/featureflags_web
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - api
